version: "3.8"

services:
  db:
    image: postgres:13-alpine
    container_name: refactor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=HIDT

  api:
    container_name: refactor_api
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/HIDT
      - SECRET_KEY=secret
      - ALGORITHM=HS256
    depends_on:
      - refactor_db

volumes:
  postgres_data:
